module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/EuojtiL98sh8MUPvDRxv8k',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.ibb.co/KxrG6Fpm/IMG-20251011-WA0084.jpg',
    NEWSLETTER_JID: '120363421928318889@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝗦𝗘𝗡𝗨 𝗠𝗗 𝗩5',
    OWNER_NAME: 'Senura',
    OWNER_NUMBER: '94743400406',
    BOT_VERSION: '5.0.0',
    BOT_FOOTER: '> 𝗦𝗘𝗡𝗨 𝗠𝗗 𝗩5',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBz0UvIyPtOZOW6TY1z',
};
